name: TNTRun
main: TNTRun\Main
version: 1.1.0
api: 4.0.0
author:
- BeckenPlayZMCPE
- MineDefenser

commands:
 tr:
   usage: /tr <addarena|regsign>
   description: TNT Run 미니게임 명령어
   permission: TNTRun.command
